### ISSUE TITLE
Mod causing crashes

### ISSUE THREAD

**Issue by Hubba-boy** [EnviroMine/EnviroMine-1.7#145]
Time: 6/8/15 7:27 PM
Description: Initializing game

java.lang.IllegalArgumentException: Failed to register dimension for id -2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at enviromine.core.EnviroMine.init(EnviroMine.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118)
	at enviromine.core.EnviroMine.init(EnviroMine.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 102305936 bytes (97 MB) / 382464000 bytes (364 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_A4 61 mods loaded, 61 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized
	betterfps{1.0.0} [BetterFps] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	LLadders{0.4.0} [Luppii's Ladders] (14166541123_Ladders-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	helpfulvillagers{1.1.4} [Helpful Villagers] (14174015954_Helpful-Villagers-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) Unloaded->Constructed->Pre-initialized->Initialized
	MCP_API{1.4} [MC+ API] ([1.7.10][1.4] MC+ API.jar) Unloaded->Constructed->Pre-initialized->Initialized
	MCP_Wheel{1.1.2} [MC+ Wheel] ([1.7.10][1.4] MC+ Wheel - v1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	MCP_Cart{1.3.0} [MC+ Cart] ([1.7.10][1.4] MC+ Cart - v1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ScoutCraft{Beta 1.3.0} [ScoutCraft] ([1.7.X] Scoutcraft Beta 1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed->Pre-initialized->Initialized
	levelup{0.4} [Level Up!] (_Level-Up-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	lightsabers{0.7.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-0.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	test{1.0} [test] (Arrow-Marker-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	atum{0.6} [Atum] (Atum-1.7.10-0.6.60.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AutoSapling{1.0} [AutoSapling] (Auto-Sapling-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BiblioCraft{1.7.3} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BoosterMod{1.0} [BoosterMod] (boostermod-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-283.jar) Unloaded->Constructed->Pre-initialized->Initialized
	C9Light{0.7.2} [C9Light] (C9Light-0.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CharacterOnGui{1.0} [CharacterOnGui] (Character-On-GUI-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
	customizablearmors{2.0} [Customizable Armors Mod] (Customizable Armors mod 2.0 - Bug fixes (1).jar) Unloaded->Constructed->Pre-initialized->Initialized
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DarkRoleplay{0.1.3} [DarkRoleplay] (DarkRoleplay-0.1.3-Pre.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DarkWorld{1.7.10-0.2} [Dark World] (DarkWorld-1.7.10-0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DeepSeaDiving{1.1.0} [DeepSeaDiving] (Deep Sea Diving 1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	emashercore{1.3.0.0} [ET Resources] (EngineersToolbox-1.2.0.6-BETA.jar) Unloaded->Constructed->Pre-initialized->Initialized
	emasherdefense{1.3.0.0} [ET Defense] (EngineersToolbox-1.2.0.6-BETA.jar) Unloaded->Constructed->Pre-initialized->Initialized
	eng_toolbox{1.2.0.6} [Engineer's Toolbox] (EngineersToolbox-1.2.0.6-BETA.jar) Unloaded->Constructed->Pre-initialized->Initialized
	gascraft{2.1.0.0} [GasCraft] (EngineersToolbox-1.2.0.6-BETA.jar) Unloaded->Constructed->Pre-initialized->Initialized
	EnndsCore{1.9.1.56-dev} [Ennds] (EnndsCore-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	enviromine{1.3.117} [EnviroMine] (EnviroMine-1.3.117.jar) Unloaded->Constructed->Pre-initialized->Errored
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ExtraPlanets{0.7} [ExtraPlanets] (ExtraPlanets-0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) Unloaded->Constructed->Pre-initialized->Initialized
	GrygrFlzr_GlowstoneWire{1.0.2.113} [Glowstone Wire] (GlowstoneWire-1.7.x-1.0.2.113.jar) Unloaded->Constructed->Pre-initialized->Initialized
	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (mam-1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	mcheli{0.9.3} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized->Initialized
	numina{0.4.0.100} [Numina] (Numina-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	powersuits{0.11.0.171} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized
	MonsterSwarm{1.0.4} [Monster Swarm] (MonsterSwarm-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ObsidianBoat{v1.3.2} [Obsidian Boat] (ObsidianBoat-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	plasmacraft{0.3.5-beta2} [PlasmaCraft] (PlasmaCraft-0.3.5-beta2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	TheLastNight{1.6} [TheLastNight] (TheLastNight_1.6-1.7.10 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized
	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) Unloaded->Constructed->Pre-initialized->Initialized
	AnimationAPI{1.2.2} [AnimationAPI] (Utility-Mobs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	UtilityMobs{3.1.0} [Utility Mobs] (Utility-Mobs-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ZAMod{v1.9.2} [Zombie Awareness] (ZombieAwareness-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CoFHCore: -[1.7.10]3.0.2-283
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: Intel Bear Lake B GL version 1.4.0 - Build 8.14.10.1930, Intel
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is supported, EXT_blend_func_separate is supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Anisotropic filtering is supported and maximum anisotropy is 4.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by jHoyne** [comment]
do you know what mod adds another dimension "-2"
"java.lang.IllegalArgumentException: Failed to register dimension for id -2, One is already registered"

**Comment by Funwayguy** [comment]
@Hubba-boy EnviroMine has configurations to change the dimension ID in the event that this kind of conflict happens. Change the ID to something that isn't used by another mod in the config and it should fix this.

@jHoyne If you actually read the stack trace log correctly you would know that EnviroMine is the one complaining.
