### ISSUE TITLE
RenderAPI and Enviromine bug

### ISSUE THREAD

**Issue by VoidsShadow** [EnviroMine/EnviroMine-1.7#99]
As soon as I updated to build 103, I couldn't launch minecraft with Enviromine due to some issue with the SmartMoving mod's render API

**Comment by VoidsShadow** [comment]
Woops! I had the wrong mod page open!

**Comment by VoidsShadow** [comment]
```YAML
[01:13:34] [Server thread/INFO] [FML]: Holder lookups applied
[01:13:39] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: enviromine.client.models.ModelPlayerEM cannot be cast to api.player.model.ModelPlayer
	at net.smart.render.playerapi.SmartRenderRenderPlayerBase.createModel(SmartRenderRenderPlayerBase.java:30) ~[SmartRenderRenderPlayerBase.class:?]
	at net.smart.render.SmartRenderRender.<init>(SmartRenderRender.java:21) ~[SmartRenderRender.class:?]
	at net.smart.render.playerapi.SmartRenderRenderPlayerBase.getRenderRender(SmartRenderRenderPlayerBase.java:24) ~[SmartRenderRenderPlayerBase.class:?]
	at net.smart.render.playerapi.SmartRenderRenderPlayerBase.renderFirstPersonArm(SmartRenderRenderPlayerBase.java:57) ~[SmartRenderRenderPlayerBase.class:?]
	at api.player.render.RenderPlayerAPI.renderFirstPersonArm(Unknown Source) ~[RenderPlayerAPI.class:?]
	at api.player.render.RenderPlayerAPI.renderFirstPersonArm(Unknown Source) ~[RenderPlayerAPI.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_82441_a(RenderPlayer.java) ~[bop.class:?]
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:531) ~[bly.class:?]
	at shadersmodcore.client.ShadersRender.renderItemFP(ShadersRender.java:86) ~[ShadersRender.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:950) ~[blt.class:?]
	at shadersmodcore.client.ShadersRender.renderHand0(ShadersRender.java:57) ~[ShadersRender.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1617) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1299) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by VoidsShadow** [comment]
It looks like build 60 works just fine.

**Comment by GenDeathrow** [comment]
Go into the config file and turn off render3d gear. I haven't tested this with smart moving. And will see if I can support this or not.

**Comment by VoidsShadow** [comment]
Darn. That was one of the features I wanted to try out.

**Comment by GenDeathrow** [comment]
They way I am rendering the camel pack right now is a temporary place holder. It was to fix a major bug. But the way I have it at the moment isn't ideal. It will be changed.

**Comment by GenDeathrow** [comment]
I will try to get a hot fix with couple other bugs.  To get it to be compatible with player API I will have to do more research to cast it properly. Thank you for patience.

**Comment by GenDeathrow** [comment]
So I have just tested with SmartMoving. and I am not getting crash. I will push a fix to not render the camel pack if its installed.. but I don't know what to say.. I noticed GalacticCraft had a similar issue that didn't seem to get figured out either. Maybe show a Mod List of what else you have installed.

https://github.com/micdoodle8/Galacticraft/issues/961

**Comment by GenDeathrow** [comment]
Version 104 should catch the Error / turn of gear rendering if the mod is installed. Its not supported yet.. but will be.

**Comment by BinToss** [comment]
Wow, I was away for way too long. Cool to hear it was fixed!
